# Generated by Django 4.2.16 on 2025-10-21 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('affiliates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatecommission',
            name='payment',
            field=models.ForeignKey(blank=True, help_text='Related payment (null for manual commissions)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='subscriptions.payment'),
        ),
    ]
