# Generated by Django 4.2.16 on 2025-10-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionplan',
            name='name',
            field=models.CharField(blank=True, help_text='Plan name', max_length=200, null=True),
        ),
    ]
